add argument as package and fix data.tar.xz

diff --git a/apt-etc-diff b/apt-etc-diff
--- a/apt-etc-diff
+++ b/apt-etc-diff
@@ -1,6 +1,46 @@
 # exit on failure
 set -e
 
+mkdir -p /tmp/debdiff
+cd /tmp/debdiff
+
+if [ "$1" == "" ]; then
+  echo "usage debdiff [package]"
+  exit
+fi
+
+package="$1"
+rm -Rf "$package"
+mkdir "$package"
+cd "$package"
+
+set -x
+
+# you could also get the file from a package mirror if you have
+#  an older version of apt-get that doesn't support 'download' 
+#  or if you would like more control over what package version
+#  you are downloading.
+# (e.g. http://archive.ubuntu.com/ubuntu/pool/main/)
+apt-get download "$package"
+
+# deb package files are ar archives
+ar vx "$package"*.deb
+# containing some compressed tar archives
+if [ -f data.tar.gz ]; then
+  tar xzf data.tar.gz
+else
+  tar xf data.tar.xz
+fi
+# now you have the files
+
+# you can get diffs for all of the files in etc if you would like
+find etc -type f |
+while read file ; do
+  diff "$file" /"$file"
+done
+# exit on failure
+set -e
+
 package=php5-fpm
 mkdir $package
 cd $package
